### ISSUE TITLE
Handling issue of not finding .git/objects inside a folder using hash-object in hash-object.cpp

### ISSUE THREAD

**Issue by RiM1604** [ENAMINE1/MY-OWN-GIT#4]
user@854aca95bd24:~/abc$ git_2.0 write-tree -w ./
Too many parmeters to write-tree.
 Usage: write-tree <file_path>
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directory: No such file or directory [.git/objects/d5]
Aborted

**Comment by ENAMINE1** [comment]
@RiM1604 we have less time left to complete it.
